import pandas as pd                                                                                                                                                      # Bring pandas into scope for this module.
DATA_FILE = "/Users/gavinwright/Desktop/School/BioAI/BIOAI Conference/cleaned_data/data_with_features.csv"                                                                                                                                                      # Assign into 'DATA_FILE'.
TEST_FROM_YEAR = 2022                                                                                                                                                      # Assign into 'TEST_FROM_YEAR'.
TEST_TO_YEAR = 2025                                                                                                                                                      # Assign into 'TEST_TO_YEAR'.
print("Loading data...")                                                                                                                                                      # Write a message to standard output.
df = pd.read_csv(DATA_FILE, low_memory=False)                                                                                                                                                      # Assign into 'df'.
df["tourney_date"] = pd.to_numeric(df["tourney_date"], errors="coerce")                                                                                                                                                      # Assign into 'df["tourney_date"]'.
df = df[df["tourney_date"].notna()].copy()                                                                                                                                                      # Assign into 'df'.
df["year"] = (df["tourney_date"] // 10000).astype(int)                                                                                                                                                      # Assign into 'df["year"]'.
test_df = df[                                                                                                                                                      # Assign into 'test_df'.
    (df["year"] >= TEST_FROM_YEAR) &                                                                                                                                                      # Open grouping to continue an expression on next lines.
    (df["year"] <= TEST_TO_YEAR)                                                                                                                                                      # Open grouping to continue an expression on next lines.
].copy().reset_index(drop=True)                                                                                                                                                      # Reset row labels to a default RangeIndex.
print(f"Found {len(test_df)} total matches from {TEST_FROM_YEAR}-{TEST_TO_YEAR}")                                                                                                                                                      # Write a message to standard output.
print(f"Test years: {sorted(test_df['year'].dropna().unique())}")                                                                                                                                                      # Write a message to standard output.
winner_rank = pd.to_numeric(test_df["winner_rank"], errors="coerce")                                                                                                                                                      # Assign into 'winner_rank'.
loser_rank = pd.to_numeric(test_df["loser_rank"], errors="coerce")                                                                                                                                                      # Assign into 'loser_rank'.
mask = winner_rank.notna() & loser_rank.notna()                                                                                                                                                      # Assign into 'mask'.
df_clean = test_df[mask].copy().reset_index(drop=True)                                                                                                                                                      # Assign into 'df_clean'.
winner_rank = winner_rank[mask].reset_index(drop=True)                                                                                                                                                      # Assign into 'winner_rank'.
loser_rank = loser_rank[mask].reset_index(drop=True)                                                                                                                                                      # Assign into 'loser_rank'.
print(f"Usable matches: {len(df_clean)}")                                                                                                                                                      # Write a message to standard output.
df_clean["surface"] = df_clean["surface"].fillna("unknown").astype(str).str.lower()                                                                                                                                                      # Assign into 'df_clean["surface"]'.
df_clean["correct"] = (winner_rank < loser_rank).astype(int)                                                                                                                                                      # Assign into 'df_clean["correct"]'.
correct = int(df_clean["correct"].sum())                                                                                                                                                      # Assign into 'correct'.
total = len(df_clean)                                                                                                                                                      # Assign into 'total'.
accuracy = correct / total * 100 if total > 0 else 0                                                                                                                                                      # Assign into 'accuracy'.
print("\n" + "=" * 50)                                                                                                                                                      # Write a message to standard output.
print("OVERALL RESULTS")                                                                                                                                                      # Write a message to standard output.
print(f"Correct: {correct}")                                                                                                                                                      # Write a message to standard output.
print(f"Total:   {total}")                                                                                                                                                      # Write a message to standard output.
print(f"Accuracy: {accuracy:.2f}%")                                                                                                                                                      # Write a message to standard output.
print("=" * 50)                                                                                                                                                      # Write a message to standard output.
print("\nYEARLY ACCURACY:")                                                                                                                                                      # Write a message to standard output.
print(f"{'Year':<8}{'Correct':>10}{'Total':>10}{'Accuracy':>12}")                                                                                                                                                      # Write a message to standard output.
print("-" * 40)                                                                                                                                                      # Write a message to standard output.
year_summary = df_clean.groupby("year")["correct"].agg(["sum", "count"]).reset_index()                                                                                                                                                      # Assign into 'year_summary'.
for _, row in year_summary.iterrows():                                                                                                                                                      # Loop over an iterable, running the block each iteration.
    year = int(row["year"])                                                                                                                                                      # Assign into 'year'.
    yr_correct = int(row["sum"])                                                                                                                                                      # Assign into 'yr_correct'.
    yr_total = int(row["count"])                                                                                                                                                      # Assign into 'yr_total'.
    yr_acc = (yr_correct / yr_total) * 100 if yr_total > 0 else 0                                                                                                                                                      # Assign into 'yr_acc'.
    print(f"{year:<8}{yr_correct:>10}{yr_total:>10}{yr_acc:>11.2f}%")                                                                                                                                                      # Write a message to standard output.
print("\nSURFACE ACCURACY:")                                                                                                                                                      # Write a message to standard output.
print(f"{'Surface':<12}{'Correct':>10}{'Total':>10}{'Accuracy':>12}")                                                                                                                                                      # Write a message to standard output.
print("-" * 44)                                                                                                                                                      # Write a message to standard output.
surface_summary = df_clean.groupby("surface")["correct"].agg(["sum", "count"]).reset_index()                                                                                                                                                      # Assign into 'surface_summary'.
for _, row in surface_summary.iterrows():                                                                                                                                                      # Loop over an iterable, running the block each iteration.
    surface = row["surface"]                                                                                                                                                      # Assign into 'surface'.
    surf_correct = int(row["sum"])                                                                                                                                                      # Assign into 'surf_correct'.
    surf_total = int(row["count"])                                                                                                                                                      # Assign into 'surf_total'.
    surf_acc = (surf_correct / surf_total) * 100 if surf_total > 0 else 0                                                                                                                                                      # Assign into 'surf_acc'.
    print(f"{surface:<12}{surf_correct:>10}{surf_total:>10}{surf_acc:>11.2f}%")                                                                                                                                                      # Write a message to standard output.
