import os                                                                                                                                                      # Bring os into scope for this module.
import json                                                                                                                                                      # Bring json into scope for this module.
import numpy as np                                                                                                                                                      # Bring numpy into scope for this module.
import pandas as pd                                                                                                                                                      # Bring pandas into scope for this module.
import joblib                                                                                                                                                      # Bring joblib into scope for this module.
from tensorflow import keras                                                                                                                                                      # Bring tensorflow into scope for this module.
DATA_FILE = "/Users/gavinwright/Desktop/School/BioAI/BIOAI Conference/cleaned_data/data_with_features.csv"                                                                                                                                                      # Assign into 'DATA_FILE'.
MODELS_DIR = "/Users/gavinwright/Desktop/School/BioAI/BIOAI Conference/Code/Models"                                                                                                                                                      # Assign into 'MODELS_DIR'.
TEST_FROM_YEAR = 2026                                                                                                                                                      # Assign into 'TEST_FROM_YEAR'.
TEST_TO_YEAR = 2026                                                                                                                                                      # Assign into 'TEST_TO_YEAR'.
print("Loading thresholds...")                                                                                                                                                      # Write a message to standard output.
with open(os.path.join(MODELS_DIR, "surface_thresholds.json"), "r") as f:                                                                                                                                                      # Enter a context manager with automatic cleanup on exit.
    thresholds = json.load(f)                                                                                                                                                      # Assign into 'thresholds'.
HARD_THRESHOLD = float(thresholds["hard"])                                                                                                                                                      # Assign into 'HARD_THRESHOLD'.
CLAY_THRESHOLD = float(thresholds["clay"])                                                                                                                                                      # Assign into 'CLAY_THRESHOLD'.
print("Loading hard and clay models...")                                                                                                                                                      # Write a message to standard output.
hard_model = keras.models.load_model(os.path.join(MODELS_DIR, "model_hard.keras"))                                                                                                                                                      # Assign into 'hard_model'.
hard_scaler = joblib.load(os.path.join(MODELS_DIR, "scaler_hard.pkl"))                                                                                                                                                      # Assign into 'hard_scaler'.
clay_model = keras.models.load_model(os.path.join(MODELS_DIR, "model_clay.keras"))                                                                                                                                                      # Assign into 'clay_model'.
clay_scaler = joblib.load(os.path.join(MODELS_DIR, "scaler_clay.pkl"))                                                                                                                                                      # Assign into 'clay_scaler'.
print("Loading data...")                                                                                                                                                      # Write a message to standard output.
df = pd.read_csv(DATA_FILE, low_memory=False)                                                                                                                                                      # Assign into 'df'.
df["tourney_date"] = pd.to_numeric(df["tourney_date"], errors="coerce")                                                                                                                                                      # Assign into 'df["tourney_date"]'.
df["year"] = (df["tourney_date"] // 10000).astype(int)                                                                                                                                                      # Assign into 'df["year"]'.
df["surface"] = df["surface"].astype(str).str.lower().str.strip()                                                                                                                                                      # Assign into 'df["surface"]'.
test_df = df[                                                                                                                                                      # Assign into 'test_df'.
    (df["year"] >= TEST_FROM_YEAR) &                                                                                                                                                      # Open grouping to continue an expression on next lines.
    (df["year"] <= TEST_TO_YEAR) &                                                                                                                                                      # Open grouping to continue an expression on next lines.
    (df["surface"].isin(["hard", "clay", "grass"]))                                                                                                                                                      # Open grouping to continue an expression on next lines.
].copy().reset_index(drop=True)                                                                                                                                                      # Reset row labels to a default RangeIndex.
print(f"Testing on {len(test_df)} matches...")                                                                                                                                                      # Write a message to standard output.
def safe(df, col, fill=0.0):                                                                                                                                                      # Define function safe for reuse.
    if col in df.columns:                                                                                                                                                      # Conditional branch based on a boolean condition.
        return pd.to_numeric(df[col], errors="coerce").fillna(fill).values.astype(np.float32)                                                                                                                                                      # Send this value back to the caller.
    return np.full(len(df), fill, dtype=np.float32)                                                                                                                                                      # Send this value back to the caller.
def build_hard_features(frame):                                                                                                                                                      # Define function build_hard_features for reuse.
    elo_diff = (                                                                                                                                                      # Assign into 'elo_diff'.
        safe(frame, "winner_elo", 1500.0) -                                                                                                                                                      # Elo rating feature for the winner or loser.
        safe(frame, "loser_elo", 1500.0)                                                                                                                                                      # Elo rating feature for the winner or loser.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    recent_elo_diff = (                                                                                                                                                      # Assign into 'recent_elo_diff'.
        safe(frame, "winner_recent_elo", 1500.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_recent_elo", 1500.0)                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    hard_elo_diff = (                                                                                                                                                      # Assign into 'hard_elo_diff'.
        safe(frame, "winner_hard_elo", 1500.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_hard_elo", 1500.0)                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    rank_diff = (                                                                                                                                                      # Assign into 'rank_diff'.
        safe(frame, "loser_rank", 2000.0) -                                                                                                                                                      # Ranking feature; lower rank number means stronger player.
        safe(frame, "winner_rank", 2000.0)                                                                                                                                                      # Ranking feature; lower rank number means stronger player.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    rank_points_diff = (                                                                                                                                                      # Assign into 'rank_points_diff'.
        safe(frame, "winner_rank_points", 0.0) -                                                                                                                                                      # Ranking feature; lower rank number means stronger player.
        safe(frame, "loser_rank_points", 0.0)                                                                                                                                                      # Ranking feature; lower rank number means stronger player.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    h2h_diff = np.clip(                                                                                                                                                      # Assign into 'h2h_diff'.
        safe(frame, "h2h_winner_wins", 0.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "h2h_loser_wins", 0.0),                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        -10,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        10                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    days_rest_diff = np.clip(                                                                                                                                                      # Assign into 'days_rest_diff'.
        safe(frame, "winner_days_rest", 7.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_days_rest", 7.0),                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        -60,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        60                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    X = np.column_stack([                                                                                                                                                      # Assign into 'X'.
        elo_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        recent_elo_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        hard_elo_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        rank_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        rank_points_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        h2h_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        days_rest_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
    ]).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    return X                                                                                                                                                      # Send this value back to the caller.
def build_clay_features(frame):                                                                                                                                                      # Define function build_clay_features for reuse.
    surf = frame["surface"].astype(str).str.lower().str.strip()                                                                                                                                                      # Assign into 'surf'.
    elo_diff = (                                                                                                                                                      # Assign into 'elo_diff'.
        safe(frame, "winner_elo", 1500.0) -                                                                                                                                                      # Elo rating feature for the winner or loser.
        safe(frame, "loser_elo", 1500.0)                                                                                                                                                      # Elo rating feature for the winner or loser.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    recent_elo_diff = (                                                                                                                                                      # Assign into 'recent_elo_diff'.
        safe(frame, "winner_recent_elo", 1500.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_recent_elo", 1500.0)                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    gs_elo_diff = (                                                                                                                                                      # Assign into 'gs_elo_diff'.
        safe(frame, "winner_gs_elo", 1500.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_gs_elo", 1500.0)                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    hard_elo_diff = (                                                                                                                                                      # Assign into 'hard_elo_diff'.
        safe(frame, "winner_hard_elo", 1500.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_hard_elo", 1500.0)                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    clay_elo_diff = (                                                                                                                                                      # Assign into 'clay_elo_diff'.
        safe(frame, "winner_clay_elo", 1500.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_clay_elo", 1500.0)                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    grass_elo_diff = (                                                                                                                                                      # Assign into 'grass_elo_diff'.
        safe(frame, "winner_grass_elo", 1500.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_grass_elo", 1500.0)                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    surface_elo_diff = np.where(                                                                                                                                                      # Assign into 'surface_elo_diff'.
        surf == "hard",                                                                                                                                                      # Assign into 'surf'.
        hard_elo_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        np.where(surf == "clay", clay_elo_diff, grass_elo_diff)                                                                                                                                                      # Pick elements from two arrays based on a boolean condition.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    rank_diff = (                                                                                                                                                      # Assign into 'rank_diff'.
        safe(frame, "loser_rank", 2000.0) -                                                                                                                                                      # Ranking feature; lower rank number means stronger player.
        safe(frame, "winner_rank", 2000.0)                                                                                                                                                      # Ranking feature; lower rank number means stronger player.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    rank_points_diff = (                                                                                                                                                      # Assign into 'rank_points_diff'.
        safe(frame, "winner_rank_points", 0.0) -                                                                                                                                                      # Ranking feature; lower rank number means stronger player.
        safe(frame, "loser_rank_points", 0.0)                                                                                                                                                      # Ranking feature; lower rank number means stronger player.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    h2h_diff = np.clip(                                                                                                                                                      # Assign into 'h2h_diff'.
        safe(frame, "h2h_winner_wins", 0.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "h2h_loser_wins", 0.0),                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        -10,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        10                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    days_rest_diff = np.clip(                                                                                                                                                      # Assign into 'days_rest_diff'.
        safe(frame, "winner_days_rest", 7.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_days_rest", 7.0),                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        -60,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        60                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    surface_wr_diff = (                                                                                                                                                      # Assign into 'surface_wr_diff'.
        safe(frame, "winner_surface_winrate", 0.5) -                                                                                                                                                      # Rolling win rate on a surface from recent history.
        safe(frame, "loser_surface_winrate", 0.5)                                                                                                                                                      # Rolling win rate on a surface from recent history.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    age_diff = (                                                                                                                                                      # Assign into 'age_diff'.
        safe(frame, "winner_age", 25.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_age", 25.0)                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    X = np.column_stack([                                                                                                                                                      # Assign into 'X'.
        elo_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        recent_elo_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        surface_elo_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        gs_elo_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        rank_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        rank_points_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        h2h_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        days_rest_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        surface_wr_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        age_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
    ]).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    return X                                                                                                                                                      # Send this value back to the caller.
all_parts = []                                                                                                                                                      # Assign into 'all_parts'.
for surface in ["hard", "clay", "grass"]:                                                                                                                                                      # Loop over an iterable, running the block each iteration.
    sdf = test_df[test_df["surface"] == surface].copy().reset_index(drop=True)                                                                                                                                                      # Assign into 'sdf'.
    if len(sdf) == 0:                                                                                                                                                      # Conditional branch based on a boolean condition.
        continue                                                                                                                                                      # Skip to the next loop iteration.
    print(f"Running {surface} model on {len(sdf)} matches...")                                                                                                                                                      # Write a message to standard output.
    if surface == "grass":                                                                                                                                                      # Conditional branch based on a boolean condition.
        winner_elo = safe(sdf, "winner_elo", 1500.0)                                                                                                                                                      # Assign into 'winner_elo'.
        loser_elo = safe(sdf, "loser_elo", 1500.0)                                                                                                                                                      # Assign into 'loser_elo'.
        preds = (winner_elo > loser_elo).astype(int)                                                                                                                                                      # Assign into 'preds'.
        probs = np.where(preds == 1, 1.0, 0.0).astype(np.float32)                                                                                                                                                      # Assign into 'probs'.
        sdf["correct"] = (preds == 1).astype(int)                                                                                                                                                      # Assign into 'sdf["correct"]'.
        sdf["prob"] = probs                                                                                                                                                      # Assign into 'sdf["prob"]'.
        sdf["threshold_used"] = np.nan                                                                                                                                                      # Assign into 'sdf["threshold_used"]'.
        all_parts.append(sdf)                                                                                                                                                      # Append one element to a growing list.
        continue                                                                                                                                                      # Skip to the next loop iteration.
    if surface == "hard":                                                                                                                                                      # Conditional branch based on a boolean condition.
        X = build_hard_features(sdf)                                                                                                                                                      # Assign into 'X'.
        mask = ~np.isnan(X).any(axis=1)                                                                                                                                                      # Assign into 'mask'.
        X_clean = X[mask]                                                                                                                                                      # Assign into 'X_clean'.
        sdf_clean = sdf[mask].copy().reset_index(drop=True)                                                                                                                                                      # Assign into 'sdf_clean'.
        X_scaled = hard_scaler.transform(X_clean)                                                                                                                                                      # Assign into 'X_scaled'.
        probs = hard_model.predict(X_scaled, verbose=0).flatten()                                                                                                                                                      # Assign into 'probs'.
        preds = (probs > HARD_THRESHOLD).astype(int)                                                                                                                                                      # Assign into 'preds'.
        sdf_clean["threshold_used"] = HARD_THRESHOLD                                                                                                                                                      # Assign into 'sdf_clean["threshold_used"]'.
    else:                                                                                                                                                      # Alternate branch when prior conditions were false.
        X = build_clay_features(sdf)                                                                                                                                                      # Assign into 'X'.
        mask = ~np.isnan(X).any(axis=1)                                                                                                                                                      # Assign into 'mask'.
        X_clean = X[mask]                                                                                                                                                      # Assign into 'X_clean'.
        sdf_clean = sdf[mask].copy().reset_index(drop=True)                                                                                                                                                      # Assign into 'sdf_clean'.
        X_scaled = clay_scaler.transform(X_clean)                                                                                                                                                      # Assign into 'X_scaled'.
        probs = clay_model.predict(X_scaled, verbose=0).flatten()                                                                                                                                                      # Assign into 'probs'.
        preds = (probs > CLAY_THRESHOLD).astype(int)                                                                                                                                                      # Assign into 'preds'.
        sdf_clean["threshold_used"] = CLAY_THRESHOLD                                                                                                                                                      # Assign into 'sdf_clean["threshold_used"]'.
    sdf_clean["correct"] = (preds == 1).astype(int)                                                                                                                                                      # Assign into 'sdf_clean["correct"]'.
    sdf_clean["prob"] = probs                                                                                                                                                      # Assign into 'sdf_clean["prob"]'.
    all_parts.append(sdf_clean)                                                                                                                                                      # Append one element to a growing list.
results = pd.concat(all_parts, ignore_index=True)                                                                                                                                                      # Assign into 'results'.
correct = int(results["correct"].sum())                                                                                                                                                      # Assign into 'correct'.
total = len(results)                                                                                                                                                      # Assign into 'total'.
accuracy = correct / total * 100 if total > 0 else 0                                                                                                                                                      # Assign into 'accuracy'.
print("\n" + "=" * 50)                                                                                                                                                      # Write a message to standard output.
print("OVERALL RESULTS")                                                                                                                                                      # Write a message to standard output.
print(f"Correct: {correct}")                                                                                                                                                      # Write a message to standard output.
print(f"Total:   {total}")                                                                                                                                                      # Write a message to standard output.
print(f"Accuracy: {accuracy:.2f}%")                                                                                                                                                      # Write a message to standard output.
print("=" * 50)                                                                                                                                                      # Write a message to standard output.
print("\nYEARLY ACCURACY:")                                                                                                                                                      # Write a message to standard output.
print(f"{'Year':<6} {'Correct':>10} {'Total':>10} {'Accuracy':>10}")                                                                                                                                                      # Write a message to standard output.
print("-" * 40)                                                                                                                                                      # Write a message to standard output.
year_summary = results.groupby("year")["correct"].agg(["sum", "count"])                                                                                                                                                      # Assign into 'year_summary'.
for year, row in year_summary.iterrows():                                                                                                                                                      # Loop over an iterable, running the block each iteration.
    yr_correct = int(row["sum"])                                                                                                                                                      # Assign into 'yr_correct'.
    yr_total = int(row["count"])                                                                                                                                                      # Assign into 'yr_total'.
    yr_acc = (yr_correct / yr_total) * 100 if yr_total > 0 else 0                                                                                                                                                      # Assign into 'yr_acc'.
    print(f"{year:<6} {yr_correct:>10} {yr_total:>10} {yr_acc:>9.2f}%")                                                                                                                                                      # Write a message to standard output.
print("\nSURFACE ACCURACY:")                                                                                                                                                      # Write a message to standard output.
print(f"{'Surface':<10} {'Correct':>10} {'Total':>10} {'Accuracy':>10}")                                                                                                                                                      # Write a message to standard output.
print("-" * 40)                                                                                                                                                      # Write a message to standard output.
surface_summary = results.groupby("surface")["correct"].agg(["sum", "count"])                                                                                                                                                      # Assign into 'surface_summary'.
for surface, row in surface_summary.iterrows():                                                                                                                                                      # Loop over an iterable, running the block each iteration.
    s_correct = int(row["sum"])                                                                                                                                                      # Assign into 's_correct'.
    s_total = int(row["count"])                                                                                                                                                      # Assign into 's_total'.
    s_acc = (s_correct / s_total) * 100 if s_total > 0 else 0                                                                                                                                                      # Assign into 's_acc'.
    print(f"{surface:<10} {s_correct:>10} {s_total:>10} {s_acc:>9.2f}%")                                                                                                                                                      # Write a message to standard output.
results_2026 = results[results["year"] == 2026]
if "match_id" not in results_2026.columns:
    results_2026 = results_2026.copy()
    results_2026["match_id"] = results_2026.index.astype(str)
predictions_2026 = results_2026[["match_id", "surface", "year", "prob", "correct"]].copy()
output_path = "gambling/2026_predictions.csv"
os.makedirs("gambling", exist_ok=True)
predictions_2026.to_csv(output_path, index=False)
print(f"\nSaved {len(predictions_2026)} rows to {output_path}")
print(predictions_2026.head())
