import os                                                                                                                                                      # Bring os into scope for this module.
import json                                                                                                                                                      # Bring json into scope for this module.
import numpy as np                                                                                                                                                      # Bring numpy into scope for this module.
import pandas as pd                                                                                                                                                      # Bring pandas into scope for this module.
import joblib                                                                                                                                                      # Bring joblib into scope for this module.
import tensorflow as tf                                                                                                                                                      # Bring tensorflow into scope for this module.
from sklearn.preprocessing import StandardScaler                                                                                                                                                      # Bring sklearn into scope for this module.
from tensorflow import keras                                                                                                                                                      # Bring tensorflow into scope for this module.
from tensorflow.keras import regularizers                                                                                                                                                      # Bring tensorflow into scope for this module.
DATA_FILE = "/Users/gavinwright/Desktop/School/BioAI/BIOAI Conference/cleaned_data/data_with_features.csv"                                                                                                                                                      # Assign into 'DATA_FILE'.
MODELS_DIR = "/Users/gavinwright/Desktop/School/BioAI/BIOAI Conference/Code/Models"                                                                                                                                                      # Assign into 'MODELS_DIR'.
TEST_FROM_YEAR = 2026                                                                                                                                                      # Assign into 'TEST_FROM_YEAR'.
TEST_TO_YEAR = 2026                                                                                                                                                      # Assign into 'TEST_TO_YEAR'.
TRAIN_FROM_YEAR = 2000
TRAIN_TO_YEAR = TEST_FROM_YEAR - 1
SEED = 42                                                                                                                                                      # Assign into 'SEED'.
np.random.seed(SEED)                                                                                                                                                      # Set random seed for reproducible stochastic behavior.
tf.random.set_seed(SEED)                                                                                                                                                      # Set random seed for reproducible stochastic behavior.
os.makedirs(MODELS_DIR, exist_ok=True)                                                                                                                                                      # Create the models output directory if missing (including parents).
print("Loading data...")                                                                                                                                                      # Write a message to standard output.
df = pd.read_csv(DATA_FILE, low_memory=False)                                                                                                                                                      # Assign into 'df'.
df["tourney_date"] = pd.to_numeric(df["tourney_date"], errors="coerce")                                                                                                                                                      # Assign into 'df["tourney_date"]'.
df["year"] = (df["tourney_date"] // 10000).astype(int)                                                                                                                                                      # Assign into 'df["year"]'.
df["surface"] = df["surface"].astype(str).str.lower().str.strip()                                                                                                                                                      # Assign into 'df["surface"]'.
df = df[(df["year"] >= TRAIN_FROM_YEAR) & (df["year"] <= TEST_TO_YEAR)].copy()                                                                                                                                                      # Assign into 'df'.
df = df[df["surface"].isin(["hard", "clay", "grass"])].copy()                                                                                                                                                      # Assign into 'df'.
df = df.sort_values("tourney_date").reset_index(drop=True)                                                                                                                                                      # Assign into 'df'.
print(f"Total rows: {len(df)}")                                                                                                                                                      # Write a message to standard output.
def safe(frame, col, fill=0.0):                                                                                                                                                      # Define function safe for reuse.
    if col in frame.columns:                                                                                                                                                      # Conditional branch based on a boolean condition.
        return pd.to_numeric(frame[col], errors="coerce").fillna(fill).values.astype(np.float32)                                                                                                                                                      # Send this value back to the caller.
    return np.full(len(frame), fill, dtype=np.float32)                                                                                                                                                      # Send this value back to the caller.
def build_hard_features(frame):                                                                                                                                                      # Define function build_hard_features for reuse.
    elo_diff = (                                                                                                                                                      # Assign into 'elo_diff'.
        safe(frame, "winner_elo", 1500.0) -                                                                                                                                                      # Elo rating feature for the winner or loser.
        safe(frame, "loser_elo", 1500.0)                                                                                                                                                      # Elo rating feature for the winner or loser.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    recent_elo_diff = (                                                                                                                                                      # Assign into 'recent_elo_diff'.
        safe(frame, "winner_recent_elo", 1500.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_recent_elo", 1500.0)                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    hard_elo_diff = (                                                                                                                                                      # Assign into 'hard_elo_diff'.
        safe(frame, "winner_hard_elo", 1500.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_hard_elo", 1500.0)                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    rank_diff = (                                                                                                                                                      # Assign into 'rank_diff'.
        safe(frame, "loser_rank", 2000.0) -                                                                                                                                                      # Ranking feature; lower rank number means stronger player.
        safe(frame, "winner_rank", 2000.0)                                                                                                                                                      # Ranking feature; lower rank number means stronger player.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    rank_points_diff = (                                                                                                                                                      # Assign into 'rank_points_diff'.
        safe(frame, "winner_rank_points", 0.0) -                                                                                                                                                      # Ranking feature; lower rank number means stronger player.
        safe(frame, "loser_rank_points", 0.0)                                                                                                                                                      # Ranking feature; lower rank number means stronger player.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    h2h_diff = np.clip(                                                                                                                                                      # Assign into 'h2h_diff'.
        safe(frame, "h2h_winner_wins", 0.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "h2h_loser_wins", 0.0),                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        -10,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        10                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    days_rest_diff = np.clip(                                                                                                                                                      # Assign into 'days_rest_diff'.
        safe(frame, "winner_days_rest", 7.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_days_rest", 7.0),                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        -60,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        60                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    X = np.column_stack([                                                                                                                                                      # Assign into 'X'.
        elo_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        recent_elo_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        hard_elo_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        rank_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        rank_points_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        h2h_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        days_rest_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
    ]).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    return X                                                                                                                                                      # Send this value back to the caller.
def build_clay_features(frame):                                                                                                                                                      # Define function build_clay_features for reuse.
    surf = frame["surface"].astype(str).str.lower().str.strip()                                                                                                                                                      # Assign into 'surf'.
    elo_diff = (                                                                                                                                                      # Assign into 'elo_diff'.
        safe(frame, "winner_elo", 1500.0) -                                                                                                                                                      # Elo rating feature for the winner or loser.
        safe(frame, "loser_elo", 1500.0)                                                                                                                                                      # Elo rating feature for the winner or loser.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    recent_elo_diff = (                                                                                                                                                      # Assign into 'recent_elo_diff'.
        safe(frame, "winner_recent_elo", 1500.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_recent_elo", 1500.0)                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    gs_elo_diff = (                                                                                                                                                      # Assign into 'gs_elo_diff'.
        safe(frame, "winner_gs_elo", 1500.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_gs_elo", 1500.0)                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    hard_elo_diff = (                                                                                                                                                      # Assign into 'hard_elo_diff'.
        safe(frame, "winner_hard_elo", 1500.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_hard_elo", 1500.0)                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    clay_elo_diff = (                                                                                                                                                      # Assign into 'clay_elo_diff'.
        safe(frame, "winner_clay_elo", 1500.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_clay_elo", 1500.0)                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    grass_elo_diff = (                                                                                                                                                      # Assign into 'grass_elo_diff'.
        safe(frame, "winner_grass_elo", 1500.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_grass_elo", 1500.0)                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    surface_elo_diff = np.where(                                                                                                                                                      # Assign into 'surface_elo_diff'.
        surf == "hard",                                                                                                                                                      # Assign into 'surf'.
        hard_elo_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        np.where(surf == "clay", clay_elo_diff, grass_elo_diff)                                                                                                                                                      # Pick elements from two arrays based on a boolean condition.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    rank_diff = (                                                                                                                                                      # Assign into 'rank_diff'.
        safe(frame, "loser_rank", 2000.0) -                                                                                                                                                      # Ranking feature; lower rank number means stronger player.
        safe(frame, "winner_rank", 2000.0)                                                                                                                                                      # Ranking feature; lower rank number means stronger player.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    rank_points_diff = (                                                                                                                                                      # Assign into 'rank_points_diff'.
        safe(frame, "winner_rank_points", 0.0) -                                                                                                                                                      # Ranking feature; lower rank number means stronger player.
        safe(frame, "loser_rank_points", 0.0)                                                                                                                                                      # Ranking feature; lower rank number means stronger player.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    h2h_diff = np.clip(                                                                                                                                                      # Assign into 'h2h_diff'.
        safe(frame, "h2h_winner_wins", 0.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "h2h_loser_wins", 0.0),                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        -10,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        10                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    days_rest_diff = np.clip(                                                                                                                                                      # Assign into 'days_rest_diff'.
        safe(frame, "winner_days_rest", 7.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_days_rest", 7.0),                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        -60,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        60                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    surface_wr_diff = (                                                                                                                                                      # Assign into 'surface_wr_diff'.
        safe(frame, "winner_surface_winrate", 0.5) -                                                                                                                                                      # Rolling win rate on a surface from recent history.
        safe(frame, "loser_surface_winrate", 0.5)                                                                                                                                                      # Rolling win rate on a surface from recent history.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    age_diff = (                                                                                                                                                      # Assign into 'age_diff'.
        safe(frame, "winner_age", 25.0) -                                                                                                                                                      # Execute this statement as part of the program logic.
        safe(frame, "loser_age", 25.0)                                                                                                                                                      # Execute this statement as part of the program logic.
    ).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    X = np.column_stack([                                                                                                                                                      # Assign into 'X'.
        elo_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        recent_elo_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        surface_elo_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        gs_elo_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        rank_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        rank_points_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        h2h_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        days_rest_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        surface_wr_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        age_diff,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
    ]).astype(np.float32)                                                                                                                                                      # Cast array/Series values to a new dtype.
    return X                                                                                                                                                      # Send this value back to the caller.
def augment_with_swap(X):                                                                                                                                                      # Define function augment_with_swap for reuse.
    swap = np.random.rand(len(X)) < 0.5                                                                                                                                                      # Assign into 'swap'.
    X_aug = np.where(swap[:, None], -X, X).astype(np.float32)                                                                                                                                                      # Assign into 'X_aug'.
    y_aug = np.where(swap, 0.0, 1.0).astype(np.float32)                                                                                                                                                      # Assign into 'y_aug'.
    return X_aug, y_aug                                                                                                                                                      # Send this value back to the caller.
def build_hard_model(input_dim):                                                                                                                                                      # Define function build_hard_model for reuse.
    model = keras.Sequential([                                                                                                                                                      # Assign into 'model'.
        keras.layers.Input(shape=(input_dim,)),                                                                                                                                                      # Keras layer or model-building API usage.
        keras.layers.Dense(64, activation="relu", kernel_regularizer=regularizers.l2(1e-4)),                                                                                                                                                      # Keras layer or model-building API usage.
        keras.layers.BatchNormalization(),                                                                                                                                                      # Keras layer or model-building API usage.
        keras.layers.Dropout(0.10),                                                                                                                                                      # Keras layer or model-building API usage.
        keras.layers.Dense(32, activation="relu", kernel_regularizer=regularizers.l2(1e-4)),                                                                                                                                                      # Keras layer or model-building API usage.
        keras.layers.BatchNormalization(),                                                                                                                                                      # Keras layer or model-building API usage.
        keras.layers.Dropout(0.05),                                                                                                                                                      # Keras layer or model-building API usage.
        keras.layers.Dense(16, activation="relu", kernel_regularizer=regularizers.l2(1e-4)),                                                                                                                                                      # Keras layer or model-building API usage.
        keras.layers.Dense(1, activation="sigmoid"),                                                                                                                                                      # Keras layer or model-building API usage.
    ])                                                                                                                                                      # Close a parenthesis or bracket from a wrapped expression.
    model.compile(                                                                                                                                                      # Configure optimizer, loss, and metrics for training.
        optimizer=keras.optimizers.Adam(learning_rate=0.0003),                                                                                                                                                      # Assign into 'optimizer'.
        loss="binary_crossentropy",                                                                                                                                                      # Assign into 'loss'.
        metrics=["accuracy"],                                                                                                                                                      # Assign into 'metrics'.
    )                                                                                                                                                      # Close syntax from an opening delimiter on prior lines.
    return model                                                                                                                                                      # Send this value back to the caller.
def build_clay_model(input_dim):                                                                                                                                                      # Define function build_clay_model for reuse.
    model = keras.Sequential([                                                                                                                                                      # Assign into 'model'.
        keras.layers.Input(shape=(input_dim,)),                                                                                                                                                      # Keras layer or model-building API usage.
        keras.layers.Dense(32, activation="relu", kernel_regularizer=regularizers.l2(1e-4)),                                                                                                                                                      # Keras layer or model-building API usage.
        keras.layers.BatchNormalization(),                                                                                                                                                      # Keras layer or model-building API usage.
        keras.layers.Dropout(0.15),                                                                                                                                                      # Keras layer or model-building API usage.
        keras.layers.Dense(16, activation="relu", kernel_regularizer=regularizers.l2(1e-4)),                                                                                                                                                      # Keras layer or model-building API usage.
        keras.layers.BatchNormalization(),                                                                                                                                                      # Keras layer or model-building API usage.
        keras.layers.Dropout(0.10),                                                                                                                                                      # Keras layer or model-building API usage.
        keras.layers.Dense(8, activation="relu", kernel_regularizer=regularizers.l2(1e-4)),                                                                                                                                                      # Keras layer or model-building API usage.
        keras.layers.Dense(1, activation="sigmoid"),                                                                                                                                                      # Keras layer or model-building API usage.
    ])                                                                                                                                                      # Close a parenthesis or bracket from a wrapped expression.
    model.compile(                                                                                                                                                      # Configure optimizer, loss, and metrics for training.
        optimizer=keras.optimizers.Adam(learning_rate=0.0005),                                                                                                                                                      # Assign into 'optimizer'.
        loss="binary_crossentropy",                                                                                                                                                      # Assign into 'loss'.
        metrics=["accuracy"],                                                                                                                                                      # Assign into 'metrics'.
    )                                                                                                                                                      # Close syntax from an opening delimiter on prior lines.
    return model                                                                                                                                                      # Send this value back to the caller.
def best_threshold(probs, y_true):                                                                                                                                                      # Define function best_threshold for reuse.
    best_t = 0.50                                                                                                                                                      # Assign into 'best_t'.
    best_acc = 0.0                                                                                                                                                      # Assign into 'best_acc'.
    for t in np.arange(0.40, 0.61, 0.005):                                                                                                                                                      # Loop over an iterable, running the block each iteration.
        preds = (probs > t).astype(int)                                                                                                                                                      # Assign into 'preds'.
        acc = (preds == y_true).mean()                                                                                                                                                      # Assign into 'acc'.
        if acc > best_acc:                                                                                                                                                      # Conditional branch based on a boolean condition.
            best_acc = acc                                                                                                                                                      # Assign into 'best_acc'.
            best_t = float(round(t, 3))                                                                                                                                                      # Assign into 'best_t'.
    return best_t, best_acc                                                                                                                                                      # Send this value back to the caller.
thresholds = {}                                                                                                                                                      # Assign into 'thresholds'.
for surface in ["hard", "clay"]:                                                                                                                                                      # Loop over an iterable, running the block each iteration.
    print(f"\nTraining {surface} model...")                                                                                                                                                      # Write a message to standard output.
    sdf = df[df["surface"] == surface].copy().reset_index(drop=True)                                                                                                                                                      # Assign into 'sdf'.
    train_df = sdf[(sdf["year"] >= TRAIN_FROM_YEAR) & (sdf["year"] <= TRAIN_TO_YEAR)].copy()                                                                                                                                                      # Assign into 'train_df'.
    test_df = sdf[(sdf["year"] >= TEST_FROM_YEAR) & (sdf["year"] <= TEST_TO_YEAR)].copy()                                                                                                                                                      # Assign into 'test_df'.
    print(f"{surface} train rows: {len(train_df)}")                                                                                                                                                      # Write a message to standard output.
    print(f"{surface} test-era rows: {len(test_df)}")                                                                                                                                                      # Write a message to standard output.
    if len(train_df) == 0:
        print(f"No training rows for {surface}; skipping.")
        continue
    if surface == "hard":                                                                                                                                                      # Conditional branch based on a boolean condition.
        X_train_raw = build_hard_features(train_df)                                                                                                                                                      # Assign into 'X_train_raw'.
        X_test_raw = build_hard_features(test_df)                                                                                                                                                      # Assign into 'X_test_raw'.
    else:                                                                                                                                                      # Alternate branch when prior conditions were false.
        X_train_raw = build_clay_features(train_df)                                                                                                                                                      # Assign into 'X_train_raw'.
        X_test_raw = build_clay_features(test_df)                                                                                                                                                      # Assign into 'X_test_raw'.
    X_train, y_train = augment_with_swap(X_train_raw)                                                                                                                                                      # Assign into 'X_train, y_train'.
    X_val, y_val = augment_with_swap(X_test_raw)                                                                                                                                                      # Assign into 'X_val, y_val'.
    train_mask = ~np.isnan(X_train).any(axis=1)                                                                                                                                                      # Assign into 'train_mask'.
    val_mask = ~np.isnan(X_val).any(axis=1)                                                                                                                                                      # Assign into 'val_mask'.
    X_train = X_train[train_mask]                                                                                                                                                      # Assign into 'X_train'.
    y_train = y_train[train_mask]                                                                                                                                                      # Assign into 'y_train'.
    X_val = X_val[val_mask]                                                                                                                                                      # Assign into 'X_val'.
    y_val = y_val[val_mask]                                                                                                                                                      # Assign into 'y_val'.
    if len(X_val) == 0:
        # If there are no matches for this surface in the target test year,
        # fall back to a neutral threshold so training can still complete.
        print(f"No validation rows for {surface} in {TEST_FROM_YEAR}; using threshold=0.50 fallback.")
        X_val = X_train.copy()
        y_val = y_train.copy()
        use_fallback_threshold = True
    else:
        use_fallback_threshold = False
    scaler = StandardScaler()                                                                                                                                                      # Assign into 'scaler'.
    X_train = scaler.fit_transform(X_train)                                                                                                                                                      # Assign into 'X_train'.
    X_val = scaler.transform(X_val)                                                                                                                                                      # Assign into 'X_val'.
    if surface == "hard":                                                                                                                                                      # Conditional branch based on a boolean condition.
        model = build_hard_model(X_train.shape[1])                                                                                                                                                      # Assign into 'model'.
    else:                                                                                                                                                      # Alternate branch when prior conditions were false.
        model = build_clay_model(X_train.shape[1])                                                                                                                                                      # Assign into 'model'.
    early_stop = keras.callbacks.EarlyStopping(                                                                                                                                                      # Assign into 'early_stop'.
        monitor="val_loss",                                                                                                                                                      # Assign into 'monitor'.
        patience=12,                                                                                                                                                      # Assign into 'patience'.
        restore_best_weights=True                                                                                                                                                      # Assign into 'restore_best_weights'.
    )                                                                                                                                                      # Close syntax from an opening delimiter on prior lines.
    lr_scheduler = keras.callbacks.ReduceLROnPlateau(                                                                                                                                                      # Assign into 'lr_scheduler'.
        monitor="val_loss",                                                                                                                                                      # Assign into 'monitor'.
        factor=0.5,                                                                                                                                                      # Assign into 'factor'.
        patience=4,                                                                                                                                                      # Assign into 'patience'.
        min_lr=1e-6,                                                                                                                                                      # Assign into 'min_lr'.
        verbose=1                                                                                                                                                      # Assign into 'verbose'.
    )                                                                                                                                                      # Close syntax from an opening delimiter on prior lines.
    model.fit(                                                                                                                                                      # Train the model for a number of epochs on batches.
        X_train,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        y_train,                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        validation_data=(X_val, y_val),                                                                                                                                                      # Assign into 'validation_data'.
        epochs=100,                                                                                                                                                      # Assign into 'epochs'.
        batch_size=512,                                                                                                                                                      # Assign into 'batch_size'.
        callbacks=[early_stop, lr_scheduler],                                                                                                                                                      # Assign into 'callbacks'.
        verbose=1,                                                                                                                                                      # Assign into 'verbose'.
    )                                                                                                                                                      # Close syntax from an opening delimiter on prior lines.
    val_probs = model.predict(X_val, verbose=0).flatten()                                                                                                                                                      # Assign into 'val_probs'.
    if use_fallback_threshold:
        threshold = 0.50
        val_acc = (val_probs > threshold).astype(int) == y_val
        val_acc = float(np.mean(val_acc))
    else:
        threshold, val_acc = best_threshold(val_probs, y_val)                                                                                                                                                      # Assign into 'threshold, val_acc'.
    model_path = os.path.join(MODELS_DIR, f"model_{surface}.keras")                                                                                                                                                      # Assign into 'model_path'.
    scaler_path = os.path.join(MODELS_DIR, f"scaler_{surface}.pkl")                                                                                                                                                      # Assign into 'scaler_path'.
    model.save(model_path)                                                                                                                                                      # Execute this statement as part of the program logic.
    joblib.dump(scaler, scaler_path)                                                                                                                                                      # Load or save a pickled Python object to disk.
    thresholds[surface] = threshold                                                                                                                                                      # Assign into 'thresholds[surface]'.
    print(f"{surface} threshold: {threshold}")                                                                                                                                                      # Write a message to standard output.
    print(f"{surface} validation accuracy: {val_acc * 100:.2f}%")                                                                                                                                                      # Write a message to standard output.
print("\nSaving thresholds...")                                                                                                                                                      # Write a message to standard output.
thresholds_path = os.path.join(MODELS_DIR, "surface_thresholds.json")                                                                                                                                                      # Assign into 'thresholds_path'.
with open(thresholds_path, "w") as f:                                                                                                                                                      # Enter a context manager with automatic cleanup on exit.
    json.dump(thresholds, f, indent=2)                                                                                                                                                      # Write Python objects to a file as JSON text.
print("Saved:")                                                                                                                                                      # Write a message to standard output.
print(os.path.join(MODELS_DIR, "model_hard.keras"))                                                                                                                                                      # Write a message to standard output.
print(os.path.join(MODELS_DIR, "scaler_hard.pkl"))                                                                                                                                                      # Write a message to standard output.
print(os.path.join(MODELS_DIR, "model_clay.keras"))                                                                                                                                                      # Write a message to standard output.
print(os.path.join(MODELS_DIR, "scaler_clay.pkl"))                                                                                                                                                      # Write a message to standard output.
print(thresholds_path)                                                                                                                                                      # Write a message to standard output.
print("\nGrass will still use pure Elo in step3_test.py.")                                                                                                                                                      # Write a message to standard output.
