import pandas as pd                                                                                                                                                      # Bring pandas into scope for this module.
import numpy as np                                                                                                                                                      # Bring numpy into scope for this module.
from collections import defaultdict, deque                                                                                                                                                      # Bring collections into scope for this module.
INPUT_FILE  = "/Users/gavinwright/Desktop/School/BioAI/BIOAI Conference/cleaned_data/clean_matches.csv"                                                                                                                                                      # Assign into 'INPUT_FILE'.
OUTPUT_FILE = "/Users/gavinwright/Desktop/School/BioAI/BIOAI Conference/cleaned_data/data_with_features.csv"                                                                                                                                                      # Assign into 'OUTPUT_FILE'.
RECENT_N    = 20                                                                                                                                                      # Assign into 'RECENT_N'.
SURFACE_N   = 50                                                                                                                                                      # Assign into 'SURFACE_N'.
BASE_ELO    = 1500                                                                                                                                                      # Assign into 'BASE_ELO'.
K           = 32                                                                                                                                                      # Assign into 'K'.
TRAIN_START_YEAR = 2000
TRAIN_END_YEAR = 2025
TEST_START_YEAR = 2026
TEST_END_YEAR = 2026
print("Loading data...")                                                                                                                                                      # Write a message to standard output.
df = pd.read_csv(INPUT_FILE, low_memory=False)                                                                                                                                                      # Assign into 'df'.
df["tourney_date"] = pd.to_numeric(df["tourney_date"], errors="coerce")                                                                                                                                                      # Assign into 'df["tourney_date"]'.
df["year"] = (df["tourney_date"] // 10000).astype(int)
df = df[(df["year"] >= TRAIN_START_YEAR) & (df["year"] <= TEST_END_YEAR)].copy()
df = df.sort_values("tourney_date").reset_index(drop=True)                                                                                                                                                      # Assign into 'df'.
print(f"  {len(df)} rows loaded, sorted chronologically")                                                                                                                                                      # Write a message to standard output.
serve_cols = ["w_ace","w_df","w_svpt","w_1stIn","w_1stWon","w_2ndWon","w_SvGms","w_bpSaved","w_bpFaced",                                                                                                                                                      # Assign into 'serve_cols'.
              "l_ace","l_df","l_svpt","l_1stIn","l_1stWon","l_2ndWon","l_SvGms","l_bpSaved","l_bpFaced"]                                                                                                                                                      # String element inside a bracketed literal continued on this line.
for c in serve_cols:                                                                                                                                                      # Loop over an iterable, running the block each iteration.
    if c in df.columns:                                                                                                                                                      # Conditional branch based on a boolean condition.
        df[c] = pd.to_numeric(df[c], errors="coerce")                                                                                                                                                      # Assign into 'df[c]'.
def expected_score(a, b):                                                                                                                                                      # Define function expected_score for reuse.
    return 1 / (1 + 10 ** ((b - a) / 400))                                                                                                                                                      # Send this value back to the caller.
def update_elo(w_elo, l_elo, k=K):                                                                                                                                                      # Define function update_elo for reuse.
    e = expected_score(w_elo, l_elo)                                                                                                                                                      # Assign into 'e'.
    return w_elo + k * (1 - e), l_elo + k * (0 - (1 - e))                                                                                                                                                      # Send this value back to the caller.
elo_overall  = defaultdict(lambda: BASE_ELO)                                                                                                                                                      # Assign into 'elo_overall'.
elo_surface  = defaultdict(lambda: BASE_ELO)                                                                                                                                                      # Assign into 'elo_surface'.
elo_gs       = defaultdict(lambda: BASE_ELO)                                                                                                                                                      # Assign into 'elo_gs'.
elo_recent   = defaultdict(lambda: BASE_ELO)                                                                                                                                                      # Assign into 'elo_recent'.
h2h          = defaultdict(int)                                                                                                                                                      # Assign into 'h2h'.
recent_results = defaultdict(lambda: deque(maxlen=RECENT_N))                                                                                                                                                      # Assign into 'recent_results'.
surface_history = defaultdict(lambda: deque(maxlen=SURFACE_N))                                                                                                                                                      # Assign into 'surface_history'.
last_match_date = {}                                                                                                                                                      # Assign into 'last_match_date'.
serve_history_w = defaultdict(lambda: deque(maxlen=RECENT_N))                                                                                                                                                      # Assign into 'serve_history_w'.
serve_history_l = defaultdict(lambda: deque(maxlen=RECENT_N))                                                                                                                                                      # Assign into 'serve_history_l'.
out = {                                                                                                                                                      # Assign into 'out'.
    "winner_elo": [], "loser_elo": [],                                                                                                                                                      # String element inside a bracketed literal continued on this line.
    "winner_hard_elo": [], "loser_hard_elo": [],                                                                                                                                                      # String element inside a bracketed literal continued on this line.
    "winner_clay_elo": [], "loser_clay_elo": [],                                                                                                                                                      # String element inside a bracketed literal continued on this line.
    "winner_grass_elo": [], "loser_grass_elo": [],                                                                                                                                                      # String element inside a bracketed literal continued on this line.
    "winner_gs_elo": [], "loser_gs_elo": [],                                                                                                                                                      # String element inside a bracketed literal continued on this line.
    "winner_recent_elo": [], "loser_recent_elo": [],                                                                                                                                                      # String element inside a bracketed literal continued on this line.
    "h2h_winner_wins": [], "h2h_loser_wins": [],                                                                                                                                                      # String element inside a bracketed literal continued on this line.
    "winner_surface_winrate": [], "loser_surface_winrate": [],                                                                                                                                                      # String element inside a bracketed literal continued on this line.
    "winner_days_rest": [], "loser_days_rest": [],                                                                                                                                                      # String element inside a bracketed literal continued on this line.
    "winner_ace_rate": [], "loser_ace_rate": [],                                                                                                                                                      # String element inside a bracketed literal continued on this line.
    "winner_df_rate": [], "loser_df_rate": [],                                                                                                                                                      # String element inside a bracketed literal continued on this line.
    "winner_1stIn_pct": [], "loser_1stIn_pct": [],                                                                                                                                                      # String element inside a bracketed literal continued on this line.
    "winner_1stWon_pct": [], "loser_1stWon_pct": [],                                                                                                                                                      # String element inside a bracketed literal continued on this line.
    "winner_bpSaved_pct": [], "loser_bpSaved_pct": [],                                                                                                                                                      # String element inside a bracketed literal continued on this line.
}                                                                                                                                                      # Execute this statement as part of the program logic.
def avg_serve_stat(history, idx):                                                                                                                                                      # Define function avg_serve_stat for reuse.
    vals = [h[idx] for h in history if h[idx] is not None and not np.isnan(h[idx])]                                                                                                                                                      # Assign into 'vals'.
    return np.mean(vals) if vals else np.nan                                                                                                                                                      # Send this value back to the caller.
def surface_winrate(history, surf):                                                                                                                                                      # Define function surface_winrate for reuse.
    matches = [(s, w) for s, w in history if s == surf]                                                                                                                                                      # Assign into 'matches'.
    if len(matches) < 3:                                                                                                                                                      # Conditional branch based on a boolean condition.
        return np.nan                                                                                                                                                      # Send this value back to the caller.
    return sum(w for _, w in matches) / len(matches)                                                                                                                                                      # Send this value back to the caller.
def days_since(player_id, current_date):                                                                                                                                                      # Define function days_since for reuse.
    if player_id not in last_match_date:                                                                                                                                                      # Conditional branch based on a boolean condition.
        return np.nan                                                                                                                                                      # Send this value back to the caller.
    try:                                                                                                                                                      # Begin a block where exceptions may be caught.
        last = pd.to_datetime(str(int(last_match_date[player_id])), format="%Y%m%d")                                                                                                                                                      # Assign into 'last'.
        curr = pd.to_datetime(str(int(current_date)), format="%Y%m%d")                                                                                                                                                      # Assign into 'curr'.
        return (curr - last).days                                                                                                                                                      # Send this value back to the caller.
    except Exception:                                                                                                                                                      # Handle exceptions raised in the try block.
        return np.nan                                                                                                                                                      # Send this value back to the caller.
IS_GS = {"Australian Open", "Roland Garros", "Wimbledon", "US Open"}                                                                                                                                                      # Assign into 'IS_GS'.
print("Computing features now")                                                                                                                                                      # Write a message to standard output.
for idx, row in df.iterrows():                                                                                                                                                      # Loop over an iterable, running the block each iteration.
    if idx % 20000 == 0:                                                                                                                                                      # Conditional branch based on a boolean condition.
        print(f"  {idx:,} / {len(df):,} rows...")                                                                                                                                                      # Write a message to standard output.
    wid  = row["winner_id"]                                                                                                                                                      # Assign into 'wid'.
    lid  = row["loser_id"]                                                                                                                                                      # Assign into 'lid'.
    surf = str(row.get("surface", "")).strip().lower()                                                                                                                                                      # Assign into 'surf'.
    date = row["tourney_date"]                                                                                                                                                      # Assign into 'date'.
    is_gs = str(row.get("tourney_name", "")) in IS_GS                                                                                                                                                      # Assign into 'is_gs'.
    out["winner_elo"].append(elo_overall[wid])                                                                                                                                                      # Append one element to a growing list.
    out["loser_elo"].append(elo_overall[lid])                                                                                                                                                      # Append one element to a growing list.
    out["winner_hard_elo"].append(elo_surface[(wid, "hard")])                                                                                                                                                      # Append one element to a growing list.
    out["loser_hard_elo"].append(elo_surface[(lid, "hard")])                                                                                                                                                      # Append one element to a growing list.
    out["winner_clay_elo"].append(elo_surface[(wid, "clay")])                                                                                                                                                      # Append one element to a growing list.
    out["loser_clay_elo"].append(elo_surface[(lid, "clay")])                                                                                                                                                      # Append one element to a growing list.
    out["winner_grass_elo"].append(elo_surface[(wid, "grass")])                                                                                                                                                      # Append one element to a growing list.
    out["loser_grass_elo"].append(elo_surface[(lid, "grass")])                                                                                                                                                      # Append one element to a growing list.
    out["winner_gs_elo"].append(elo_gs[wid])                                                                                                                                                      # Append one element to a growing list.
    out["loser_gs_elo"].append(elo_gs[lid])                                                                                                                                                      # Append one element to a growing list.
    out["winner_recent_elo"].append(elo_recent[wid])                                                                                                                                                      # Append one element to a growing list.
    out["loser_recent_elo"].append(elo_recent[lid])                                                                                                                                                      # Append one element to a growing list.
    key_wl = (wid, lid); key_lw = (lid, wid)                                                                                                                                                      # Assign into 'key_wl'.
    out["h2h_winner_wins"].append(h2h[key_wl])                                                                                                                                                      # Append one element to a growing list.
    out["h2h_loser_wins"].append(h2h[key_lw])                                                                                                                                                      # Append one element to a growing list.
    out["winner_surface_winrate"].append(surface_winrate(surface_history[wid], surf))                                                                                                                                                      # Append one element to a growing list.
    out["loser_surface_winrate"].append(surface_winrate(surface_history[lid], surf))                                                                                                                                                      # Append one element to a growing list.
    out["winner_days_rest"].append(days_since(wid, date))                                                                                                                                                      # Append one element to a growing list.
    out["loser_days_rest"].append(days_since(lid, date))                                                                                                                                                      # Append one element to a growing list.
    out["winner_ace_rate"].append(avg_serve_stat(serve_history_w[wid], 0))                                                                                                                                                      # Append one element to a growing list.
    out["loser_ace_rate"].append(avg_serve_stat(serve_history_w[lid], 0))                                                                                                                                                      # Append one element to a growing list.
    out["winner_df_rate"].append(avg_serve_stat(serve_history_w[wid], 1))                                                                                                                                                      # Append one element to a growing list.
    out["loser_df_rate"].append(avg_serve_stat(serve_history_w[lid], 1))                                                                                                                                                      # Append one element to a growing list.
    out["winner_1stIn_pct"].append(avg_serve_stat(serve_history_w[wid], 2))                                                                                                                                                      # Append one element to a growing list.
    out["loser_1stIn_pct"].append(avg_serve_stat(serve_history_w[lid], 2))                                                                                                                                                      # Append one element to a growing list.
    out["winner_1stWon_pct"].append(avg_serve_stat(serve_history_w[wid], 3))                                                                                                                                                      # Append one element to a growing list.
    out["loser_1stWon_pct"].append(avg_serve_stat(serve_history_w[lid], 3))                                                                                                                                                      # Append one element to a growing list.
    out["winner_bpSaved_pct"].append(avg_serve_stat(serve_history_w[wid], 4))                                                                                                                                                      # Append one element to a growing list.
    out["loser_bpSaved_pct"].append(avg_serve_stat(serve_history_w[lid], 4))                                                                                                                                                      # Append one element to a growing list.
    new_w, new_l = update_elo(elo_overall[wid], elo_overall[lid])                                                                                                                                                      # Assign into 'new_w, new_l'.
    elo_overall[wid] = new_w; elo_overall[lid] = new_l                                                                                                                                                      # Assign into 'elo_overall[wid]'.
    if surf in ("hard", "clay", "grass"):                                                                                                                                                      # Conditional branch based on a boolean condition.
        nw, nl = update_elo(elo_surface[(wid, surf)], elo_surface[(lid, surf)])                                                                                                                                                      # Assign into 'nw, nl'.
        elo_surface[(wid, surf)] = nw; elo_surface[(lid, surf)] = nl                                                                                                                                                      # Assign into 'elo_surface[(wid, surf)]'.
    if is_gs:                                                                                                                                                      # Conditional branch based on a boolean condition.
        nw, nl = update_elo(elo_gs[wid], elo_gs[lid])                                                                                                                                                      # Assign into 'nw, nl'.
        elo_gs[wid] = nw; elo_gs[lid] = nl                                                                                                                                                      # Assign into 'elo_gs[wid]'.
    nw, nl = update_elo(elo_recent[wid], elo_recent[lid], k=64)                                                                                                                                                      # Assign into 'nw, nl'.
    elo_recent[wid] = nw; elo_recent[lid] = nl                                                                                                                                                      # Assign into 'elo_recent[wid]'.
    h2h[key_wl] += 1                                                                                                                                                      # Assign into 'h2h[key_wl] +'.
    surface_history[wid].append((surf, 1))                                                                                                                                                      # Append one element to a growing list.
    surface_history[lid].append((surf, 0))                                                                                                                                                      # Append one element to a growing list.
    last_match_date[wid] = date                                                                                                                                                      # Assign into 'last_match_date[wid]'.
    last_match_date[lid] = date                                                                                                                                                      # Assign into 'last_match_date[lid]'.
    def serve_stats(ace, df, svpt, firstin, firstwon, bpsaved, bpfaced):                                                                                                                                                      # Define function serve_stats for reuse.
        if pd.isna(svpt) or svpt == 0:                                                                                                                                                      # Conditional branch based on a boolean condition.
            return (np.nan, np.nan, np.nan, np.nan, np.nan)                                                                                                                                                      # Send this value back to the caller.
        ace_r   = ace / svpt if not pd.isna(ace) else np.nan                                                                                                                                                      # Assign into 'ace_r'.
        df_r    = df / svpt if not pd.isna(df) else np.nan                                                                                                                                                      # Assign into 'df_r'.
        fin_pct = firstin / svpt if not pd.isna(firstin) else np.nan                                                                                                                                                      # Assign into 'fin_pct'.
        fw_pct  = firstwon / firstin if (not pd.isna(firstwon) and not pd.isna(firstin) and firstin > 0) else np.nan                                                                                                                                                      # Assign into 'fw_pct'.
        bp_pct  = bpsaved / bpfaced if (not pd.isna(bpsaved) and not pd.isna(bpfaced) and bpfaced > 0) else np.nan                                                                                                                                                      # Assign into 'bp_pct'.
        return (ace_r, df_r, fin_pct, fw_pct, bp_pct)                                                                                                                                                      # Send this value back to the caller.
    w_stats = serve_stats(                                                                                                                                                      # Assign into 'w_stats'.
        row.get("w_ace"), row.get("w_df"), row.get("w_svpt"),                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        row.get("w_1stIn"), row.get("w_1stWon"), row.get("w_bpSaved"), row.get("w_bpFaced")                                                                                                                                                      # Execute this statement as part of the program logic.
    )                                                                                                                                                      # Close syntax from an opening delimiter on prior lines.
    l_stats = serve_stats(                                                                                                                                                      # Assign into 'l_stats'.
        row.get("l_ace"), row.get("l_df"), row.get("l_svpt"),                                                                                                                                                      # Continue a list, tuple, or argument list on the next line.
        row.get("l_1stIn"), row.get("l_1stWon"), row.get("l_bpSaved"), row.get("l_bpFaced")                                                                                                                                                      # Execute this statement as part of the program logic.
    )                                                                                                                                                      # Close syntax from an opening delimiter on prior lines.
    serve_history_w[wid].append(w_stats)                                                                                                                                                      # Append one element to a growing list.
    serve_history_w[lid].append(l_stats)                                                                                                                                                      # Append one element to a growing list.
print("Attaching new columns...")                                                                                                                                                      # Write a message to standard output.
for col_name, values in out.items():                                                                                                                                                      # Loop over an iterable, running the block each iteration.
    df[col_name] = values                                                                                                                                                      # Assign into 'df[col_name]'.
df.to_csv(OUTPUT_FILE, index=False)                                                                                                                                                      # Write the DataFrame to a CSV file on disk.
print(f"\nDone! Saved to {OUTPUT_FILE}  ({len(df)} rows)")                                                                                                                                                      # Write a message to standard output.
print(f"New columns added: {list(out.keys())}")                                                                                                                                                      # Write a message to standard output.
